agent:
  name: reviewer-agent
  description: >
    Revisa c칩digo, sugiere cambios, escribe tests, ejecuta pruebas y reporta resultados en PRs o bajo petici칩n manual.
  triggers:
    - pull_request_opened
    - manual
  tasks:
    - run: python scripts/review_and_test.py
      description: >
        1. Revisa el c칩digo propuesto (Python, HTML, JSON).
        2. Sugiere mejoras y corrige errores.
        3. Escribe y ejecuta tests autom치ticos.
        4. Reporta comentarios y resultados en el PR.
      env:
        PYTHONPATH: src/
